AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Service CloudFormation Template

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: myContainer
          Image: nginx:latest
          PortMappings:
            - ContainerPort: 80
          Memory: 512
          Cpu: 256

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition

Outputs:
  ServiceName:
    Value: !Ref ECSService
