AWSTemplateFormatVersion: '2010-09-09'
Description: Networking CloudFormation Template

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

Outputs:
  VPCId:
    Value: !Ref VPC
